import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../core/app/routes.dart';
import '../../../core/utils/constants.dart';
import '../../../core/utils/enum.dart';
import '../../../infrastructure/entities/user_response.dart';
import '../../../infrastructure/shared/alert.dart';
import '../../../infrastructure/shared/storage.dart';
import '../service/user_service.dart';

class LoginController extends GetxController {
  // Controladores de texto para los campos
  final emailController = TextEditingController();
  final passwordController = TextEditingController();

  // Estado para mostrar/ocultar la contraseña
  var isPasswordVisible = false.obs;

  // Estado para manejar el loading
  var isLoading = false.obs;

  // Método para alternar la visibilidad de la contraseña
  void togglePasswordVisibility() {
    isPasswordVisible.value = !isPasswordVisible.value;
  }

  // Validación del correo electrónico
  String? validateEmail(String? value) {
    if (value == null || value.isEmpty) {
      return 'Por favor, ingresa tu email';
    } else if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(value)) {
      return 'Ingresa un email válido';
    }
    return null;
  }

  // Validación de la contraseña
  String? validatePassword(String? value) {
    if (value == null || value.isEmpty) {
      return 'Por favor, ingresa tu contraseña';
    } else if (value.length < 6) {
      return 'La contraseña debe tener al menos 6 caracteres';
    }
    return null;
  }

  // Método para registrar un nuevo usuario
  void register() {
    Get.toNamed("/register"); // Navega a la pantalla de registro
  }

  // Método para enviar el formulario
  Future<void> submitForm() async {
    // Validar campos antes de proceder
    final emailError = validateEmail(emailController.text);
    final passwordError = validatePassword(passwordController.text);

    if(emailError != null){
      SnackbarAlert.error(title: "Error!", message: emailError, durationSeconds: 2);
      //Get.snackbar('Error', emailError);
      return;
    }
    if(passwordError != null){
      SnackbarAlert.error(title: "Error!", message: passwordError, durationSeconds: 2);// Get.snackbar('Error', passwordError);
      return;
    }

    try {
      // Activar estado de loading
      isLoading.value = true;

      // Limpiar cualquier error previo
      LocalStorage.saveStatus(false);

      /*final apiResponse = await AuthService.login(
          emailController.text,
          passwordController.text
      );*/

      final res=await ApiService.post('auth/login', {
        'email':  emailController.text,
        'password': passwordController.text,
      });
     final apiResponse =  Autogenerated.fromJson(res);

      // Guardar datos del usuario
      LocalStorage.saveToken(apiResponse.token!);
      LocalStorage.saveUser(apiResponse.user!);
      LocalStorage.saveStatus(true);

      // Definir qué layout mostrar según el rol y departamento
      final userRole = apiResponse.user!.role;
      final userDepartment = apiResponse.user!.department;

      SnackbarAlert.success(message: "Iniciando ...");
      if(userRole == Role.SUPER_ADMIN.label){
        Get.offNamed(AppRoutes.dashboardSuperAdmin, arguments: { 'user': apiResponse.user});
      } else {
        switch (userDepartment) {
          case AppStrings.dgTecnologiaInformacion:
            Get.offNamed(AppRoutes.dashboardTecnologia, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgAdministracion:
            Get.offNamed(AppRoutes.dashboardAdministracion, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgEgreso:
            Get.offNamed(AppRoutes.dashboardEgreso, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgIngreso:
            Get.offNamed(AppRoutes.dashboardIngreso, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgCuentaUnica:
            Get.offNamed(AppRoutes.dashboardCuentaUnica, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgPlanificacionAnalisisFinanciero:
            Get.offNamed(AppRoutes.dashboardPlanificacionAnalisisFinanciero, arguments: { 'user': apiResponse.user});
            break;
          case AppStrings.dgRecursosHumanos:
            Get.offNamed(AppRoutes.dashboardRecursosHumanos, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgInversionesYValores:
            Get.offNamed(AppRoutes.dashboardInversionesValores, arguments: {'user': apiResponse.user});
            break;
          case AppStrings.dgConsultoriaJuridica:
            Get.offNamed(AppRoutes.dashboardConsultoriaJuridica, arguments: {'user': apiResponse.user});
            break;
          default:
            //Get.snackbar('Error', 'Dirección no reconocida');
            SnackbarAlert.error(title: "Error!", message: 'Dirección no reconocida', durationSeconds: 5);//
            break;
        }
      }
    } catch (e) {
     // Get.snackbar('Error', 'Error al iniciar sesión');
      print(e);

    } finally {
      // Desactivar loading siempre, tanto en éxito como en error
      isLoading.value = false;
    }
  }
  void logout(){
    LocalStorage.clear();
    LocalStorage.saveStatus(false);
    AppRoutes.navigateAndRemoveUntil("/login");
  }
}