
import 'dart:convert';
import 'package:core_system/infrastructure/shared/storage.dart';
import 'package:http/http.dart' as http;

import '../../../core/utils/constants.dart';
import '../../../infrastructure/entities/user_response.dart';

class ApiService {
  static const String _baseUrl = AppStrings.urlApi;

  // Método genérico para POST
  static Future<dynamic> post(String endpoint, Map<String, dynamic> body) async {
    final url = Uri.parse('$_baseUrl/$endpoint');

    try {
      final response = await http.post(
        url,
        headers: {'Content-Type': 'application/json'},
        body: jsonEncode(body),
      );

      return _handleResponse(response);
    } catch (e) {
      throw Exception('Error de red: $e');
    }
  }

  // Método genérico para GET
  static Future<dynamic> get(String endpoint, {Map<String, String>? queryParams}) async {
    final url = Uri.parse('$_baseUrl/$endpoint').replace(queryParameters: queryParams);

    try {
      final response = await http.get(url);
      return _handleResponse(response);
    } catch (e) {
      throw Exception('Error de red: $e');
    }
  }

  // Manejar la respuesta
  static dynamic _handleResponse(http.Response response) {
    switch (response.statusCode) {
      case 200:
        return jsonDecode(response.body);
      case 400:
        throw Exception('Bad Request: ${response.body}');
      case 401:
      case 403:
        throw Exception('No autorizado: ${response.body}');
      case 404:
        throw Exception('Recurso no encontrado');
      case 500:
        throw Exception('Error del servidor: ${response.body}');
      default:
        throw Exception('Error en la solicitud: ${response.statusCode}');
    }
  }
}

class AuthService {
  static Future<Autogenerated> login(String email, String password) async {
    try {
      final response = await ApiService.post(
        'auth/login',
        {
          'email': email,
          'password': password,
        },
      );
      // response ya es un Map<String, dynamic> (ApiService lo decodifica)
      return Autogenerated.fromJson(response);
    } catch (e) {
      rethrow;
    }
  }
  Future<void> logout() async {
    await LocalStorage.clear();
  }
}