class Autogenerated {
  bool? success;
  User? user;
  String? token;

  Autogenerated({this.success, this.user, this.token});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    user = json['user'] != null ? User.fromJson(json['user']) : null;
    token = json['token'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = success;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['token'] = token;
    return data;
  }
}

class User {
  int? id;
  late String email;
  String? password;
  late String name;
  String? role;
  String? department;
  DateTime? createdAt;
  DateTime? updatedAt;
  bool? isActive;
  String? profileImage; // Imagen de perfil (puede ser nulo)
  String? position;

  User(
      {this.id,
        required this.email,
        this.password,
        required this.name,
        this.role,
        this.department,
        this.isActive,
        this.profileImage,
        this.position,
        this.createdAt,
        this.updatedAt
      });

  User.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    email = json['email'] ?? null;
    password = json['password'];
    name = json['name'] ?? null;
    role = json['role'];
    department = json['department'];
    isActive = json['isActive'];
    profileImage = json['profileImage'];
    position = json['position'];
    // Convierte createdAt de String a DateTime?
    createdAt = json['createdAt'] is String && json['createdAt'].isNotEmpty
        ? DateTime.parse(json['createdAt'])
        : null;
    // Convierte updatedAt de String a DateTime?
    updatedAt = json['updatedAt'] is String && json['updatedAt'].isNotEmpty
        ? DateTime.parse(json['updatedAt'])
        : null;
  }

  Map<String, dynamic> toJson() {
    return {
     // 'id': id,
      'email': email,
      'password': password,
      'name': name,
      'role': role,
      'department': department,
      'isActive': isActive,
      'profileImage': profileImage,
      'position': position,
      //'createdAt': createdAt,
      //'updatedAt': updatedAt,
      //'createdAt': createdAt?.toIso8601String(), // Convierte DateTime a String
      //'updatedAt': updatedAt?.toIso8601String(), // Convierte DateTime a String
    };
  }

  User copyWith({
    int? id,
    String? name,
    String? email,
    bool? isActive,
    String? role,
    String? password,
    String? department,
    String? profileImage,
    String? position,
  }) {
    return User(
      id: id ?? this.id,
      name: name ?? this.name,
      email: email ?? this.email,
      isActive: isActive ?? this.isActive,
      role: role ?? this.role,
      password: password ?? this.password,
      department: department ?? this.department,
      profileImage: profileImage ?? this.profileImage,
      position: position ?? this.position,
      updatedAt: DateTime.now(),
    );
  }

  /*Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['email'] = email;
    data['password'] = password;
    data['name'] = name;
    data['role'] = role;
    data['department'] = department;
    data['isActive'] = isActive;
    data['profileImage'] = profileImage;
    data['position'] = position;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }*/

  @override
  String toString() {
    return 'User {id: $id, name: $name, email: $email, isActive: $isActive, rol: $role, password: ****, createdAt: $createdAt, updatedAt: $updatedAt, department: $department, profileImage: $profileImage, position: $position}';
  }
}